### ISSUE TITLE
ASPX Error compressing <%= %> tags

### ISSUE THREAD

**Issue by sirbig** [serg472/htmlcompressor#104]
Hello,

I've been using htmlcompressor to compress aspx and ascx files sucessfuly for quite sometime.
Now I had the need to add to some of the aspx files <%= %> tags and since I did that, when compressing it gives the following error:

`call java -jar htmlcompressor-1.5.3.jar --mask *.ascx;*.aspx --nomunge --compress-js --compress-css -o C:\Users\Test\Desktop\SomeFolder\Things.aspx C:\Users\Test\Desktop\SomeFolder\Things.aspx 
[ERROR] HtmlCompressor: "unterminated string literal" at line [1:2] during JavaScript compression: ">
[ERROR] HtmlCompressor: "syntax error" at line [1:2] during JavaScript compression: ">
[ERROR] HtmlCompressor: "Compilation produced 2 syntax errors." at line [1:0] during JavaScript compression
Exception in thread "main" org.mozilla.javascript.EvaluatorException: Compilation produced 2 syntax errors.
        at com.googlecode.htmlcompressor.compressor.YuiJavaScriptCompressor$DefaultErrorReporter.runtimeError(YuiJavaScriptCompressor.java:93)
        at org.mozilla.javascript.Parser.parse(Parser.java:396)
        at org.mozilla.javascript.Parser.parse(Parser.java:340)
        at com.yahoo.platform.yui.compressor.JavaScriptCompressor.parse(JavaScriptCompressor.java:315)
        at com.yahoo.platform.yui.compressor.JavaScriptCompressor.<init>(JavaScriptCompressor.java:536)
        at com.googlecode.htmlcompressor.compressor.YuiJavaScriptCompressor.compress(YuiJavaScriptCompressor.java:53)
        at com.googlecode.htmlcompressor.compressor.HtmlCompressor.compressJavaScript(HtmlCompressor.java:975)
        at com.googlecode.htmlcompressor.compressor.HtmlCompressor.processScriptBlocks(HtmlCompressor.java:910)
        at com.googlecode.htmlcompressor.compressor.HtmlCompressor.processPreservedBlocks(HtmlCompressor.java:800)
        at com.googlecode.htmlcompressor.compressor.HtmlCompressor.compress(HtmlCompressor.java:221)
        at com.googlecode.htmlcompressor.CmdLineCompressor.process(CmdLineCompressor.java:275)
        at com.googlecode.htmlcompressor.CmdLineCompressor.main(CmdLineCompressor.java:109)`

**Comment by sirbig** [comment]
Also, this is where I'm using those tags, in the header to add versioning to stylesheet files:

<link href="css/cssfile.css?v=<% Session("version") %>" rel="stylesheet" type="text/css" />

**Comment by sirbig** [comment]
Also, this is where I'm using those tags, in the header to add versioning to stylesheet files:

`<link href="css/cssfile.css?v=<% Session("version") %>" rel="stylesheet" type="text/css" />`

**Comment by sirbig** [comment]
Also, this is where I'm using those tags, in the header to add versioning to stylesheet files:

`<link href="css/cssfile.css?v=<%= Session("version") %>" rel="stylesheet" type="text/css" />`

**Comment by serg472** [comment]
Hello, try adding `--preserve-server-script` param

**Comment by sirbig** [comment]
> Hello, try adding `--preserve-server-script` param

Yup, that did the trick.
But, wasn't it supposed to automatically accept <% %> tags?
